---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:

    - name: Instalando depedências
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - snapd
        - git
        - vim
        - python3-docker
        - mysql-server-core-8.0 
        - mysql-server-8.0

    - name: Copiando script
      copy:
        src: files/zabbix.sql
        dest: /root/zabbix.sql
        owner: root
        group: root   

    - name: Copiando mysqld.cnf
      copy:
        src: files/mysqld.cnf
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        owner: root
        group: root  

    - name: restart and enable mysql service
      service:
        name: mysql
        state: restarted
        enabled: yes       

    - name: Criando base de dados
      shell: mysql -u root < ~/zabbix.sql